cc_test(
    name = "hello_greet_test",
    srcs = ["hello_greet_test.cc"],
    # copts = ["-Iexternal/gtest/include -lgtest -lgtest_main"],
    deps = [
        "//main:hello_greet",
        "@googletest//:gtest_main",
    ],
)