cc_binary(
    name = "need_of_ns",
    srcs = ["need_of_ns.cc"],
)

cc_binary(
    name = "ns_01",
    srcs = ["ns_01.cc"],
)

cc_binary(
    name = "funcs_inside_ns",
    srcs = ["funcs_inside_ns.cc"],
)

cc_binary(
    name = "class_inside_ns",
    srcs = ["class_inside_ns.cc"],
)

cc_binary(
    name = "class_declare_inside_define_outside_ns",
    srcs = ["class_declare_inside_define_outside_ns.cc"],
)

cc_binary(
    name = "def_class_method_outside_ns",
    srcs = ["def_class_method_outside_ns.cc"],
)

cc_binary(
    name = "different_ns",
    srcs = ["different_ns.cc"],
)

cc_binary(
    name = "ns_extension",
    srcs = ["ns_extension.cc"],
)

cc_binary(
    name = "unnamed_ns",
    srcs = ["unnamed_ns.cc"],
)